### ISSUE TITLE
Fatal error: Uncaught RedisException: Connection lost 

### ISSUE THREAD

**Issue by boffart** [mikopbx/Core#294]
An error occurs when running the `/etc/rc/bootup` script
```
Fatal error: Uncaught RedisException: Connection lost in /offload/rootfs/usr/www/src/Common/Models/PbxExtensionModules.php:136
Stack trace:
#0 [internal function]: Redis->get('PbxExtensionMod...')
#1 [internal function]: Phalcon\Storage\Adapter\Redis->get('PbxExtensionMod...')
#2 [internal function]: Phalcon\Mvc\Model\Query->execute()
#3 /offload/rootfs/usr/www/src/Common/Models/PbxExtensionModules.php(136): Phalcon\Mvc\Model::find(Array)
#4 /offload/rootfs/usr/www/src/Common/Models/ModelsBase.php(106): MikoPBX\Common\Models\PbxExtensionModules::getEnabledModulesArray()
#5 /offload/rootfs/usr/www/src/Common/Models/ModelsBase.php(77): MikoPBX\Common\Models\ModelsBase->addExtensionModulesRelations()
#6 /offload/rootfs/usr/www/src/Common/Models/Storage.php(99): MikoPBX\Common\Models\ModelsBase->initialize()
#7 [internal function]: MikoPBX\Common\Models\Storage->initialize()
#8 [internal function]: Phalcon\Mvc\Model\Manager->initialize(Object(MikoPBX\Common\Models\Storage))
#9 [internal function]: Phalcon\Mvc\Model->__constru in /offload/rootfs/usr/www/src/Common/Models/PbxExtensionModules.php on line 136
```

**Comment by bigshoma** [comment]
Ошибка в релизе [2022.1.99 ] воспроизводится в dockere
/offload/rootfs/usr/www/src/Common/Models/PbxExtensionModules.php:136

**Comment by boffart** [comment]
Создал [задачу](https://github.com/mikopbx/Core/issues/324) на анализ 
https://github.com/mikopbx/Core/issues/324
