### ISSUE TITLE
Fatal error: Uncaught Phalcon\Mvc\Model\Exception: Failed to store metaData to the cache adapter in /offload/rootfs/usr/www/src/Common/Models/PbxExtensionModules.php:136

### ISSUE THREAD

**Issue by ivstep** [mikopbx/Core#651]
MikoPBX 2023.1.223

Периодически перестает работать АТС: веб интерфейс не доступен, звонки не работают. При входе в веб интерфейс сообщение:

Fatal error: Uncaught Phalcon\Mvc\Model\Exception: Failed to store metaData to the cache adapter in /offload/rootfs/usr/www/src/Common/Models/PbxExtensionModules.php:136 Stack trace: #0 [internal function]: Phalcon\Mvc\Model\MetaData->throwWriteException(true) #1 [internal function]: Phalcon\Mvc\Model\MetaData->write('map-mikopbx\\com...', Array) #2 [internal function]: Phalcon\Mvc\Model\MetaData->initialize(Object(MikoPBX\Common\Models\PbxExtensionModules), NULL, NULL, NULL) #3 [internal function]: Phalcon\Mvc\Model\MetaData->readColumnMapIndex(Object(MikoPBX\Common\Models\PbxExtensionModules), 1) #4 [internal function]: Phalcon\Mvc\Model\MetaData->getReverseColumnMap(Object(MikoPBX\Common\Models\PbxExtensionModules)) #5 [internal function]: Phalcon\Mvc\Model\MetaData->hasAttribute(Object(MikoPBX\Common\Models\PbxExtensionModules), 'disabled') #6 [internal function]: Phalcon\Mvc\Model\Query->_getQualified(Array) #7 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array, true) #8 [internal function]: Phalcon\M in /offload/rootfs/usr/www/src/Common/Models/PbxExtensionModules.php on line 136

Помогает перезагрузка АТС.
Память свободная есть, redis запущен.

**Comment by boffart** [comment]
Нужно пробовать воспроизвести на актуальной версии АТС. Слишком много было переписано. 
Оперативки как я понял хватает, но вопрос что с местом на диске, точно есть запас? 

Я перенесу это в дискуссии, если воспроизведется в актуальной сборке, то тогда будем думать.

**Comment by boffart** [comment]
пробую команду:
```
redis-cli 
127.0.0.1:6379> FLUSHALL

```
появляется ошибка:
<img width="1295" alt="232" src="https://github.com/mikopbx/Core/assets/5922739/7449f5c8-a19a-4aac-b2b3-c54ee3add42a">

**Comment by boffart** [comment]
данные снэпшота сохраняются по пути `/var/tmp`
фактически, это оперативная память

тут варианты:

1. файл `/var/tmp/dump.rdb` поврежден или запись в файл не возможна
2. не хватает оперативной памяти

**Comment by Sherman120kg** [comment]
MikoPBX 2023.2.206
Ловим подобную ошибку, симптомы те же.
`Fatal error: Uncaught Phalcon\Mvc\Model\Exception: Failed to store metaData to the cache adapter in /offload/rootfs/usr/www/src/Common/Models/PbxExtensionModules.php:120 Stack trace: #0 [internal function]: Phalcon\Mvc\Model\MetaData->throwWriteException(true) #1 [internal function]: Phalcon\Mvc\Model\MetaData->write('map-mikopbx\\com...', Array) #2 [internal function]: Phalcon\Mvc\Model\MetaData->initialize(Object(MikoPBX\Common\Models\PbxExtensionModules), NULL, NULL, NULL) #3 [internal function]: Phalcon\Mvc\Model\MetaData->readColumnMapIndex(Object(MikoPBX\Common\Models\PbxExtensionModules), 1) #4 [internal function]: Phalcon\Mvc\Model\MetaData->getReverseColumnMap(Object(MikoPBX\Common\Models\PbxExtensionModules)) #5 [internal function]: Phalcon\Mvc\Model\MetaData->hasAttribute(Object(MikoPBX\Common\Models\PbxExtensionModules), 'uniqid') #6 [internal function]: Phalcon\Mvc\Model\Query->_getQualified(Array) #7 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array) #8 [internal function]: Phalcon\Mvc\Model in /offload/rootfs/usr/www/src/Common/Models/PbxExtensionModules.php on line 120`


Место на диске есть, памяти хватает. Логи могу предоставить по запросу в лс.

**Comment by boffart** [comment]
Нужно также пробовать анализировать вывод
`lsof` 
в момент возникновения ошибки, выл случай ,когда доп модуль создавал кучу открытых файлов исистемна не могла создать новый выйл, в итоге процессы перестают запускаться.

**Comment by boffart** [comment]
Похоже проблема связана с использованием доп. модулей.
Решается добавлением в cron через кастомизацию системных файлов команды
`*/1 * * * * /bin/busybox find /storage/usbdisk*/mikopbx/tmp/*/ -mmin +5 -type f -delete> /dev/null 2>&1`
чистит временные файлы.

**Comment by jorikfon** [comment]
Можно попробовать перед удалением выполнить команду для подсчета количества файлов, чтобы определить виновника. Если проблема именно в количестве.

`find /storage/usbdisk*/mikopbx/tmp/*/ -type f -printf '%h\n' | sort | uniq -c | sort -nr`

**Comment by jorikfon** [comment]
<img width="740" alt="Screenshot 2024-08-01 at 13 22 26" src="https://github.com/user-attachments/assets/95b962e5-ba13-40f0-aeba-082ebfc9875f">
В рабочей такая картинка, проблемы нет.

**Comment by jorikfon** [comment]
Ну вот рано закрывать задачу, как минимум туда надо шаги по диагностике перечислить, пока не понятна даже причина такого поведения. И почему проблема именно с редис, там много чего пишется читается в базу данных в том числе, можно перенести кеш редиса на storage, если он там еще не был ранее.

**Comment by jorikfon** [comment]
Судя по коду Phalcon можно попробовать обойти установкой переменной phalcon.orm.exception_on_failed_metadata_save => Off
Но я уверен что вылезет что-то еще...

**Comment by ivstep** [comment]
MikoPBX 2024.1.114
ПТ 1.458

Периодически выключается модуль "Панель телефонии 4.0". Ошибка на скриншоте. Логи php:

`[09-Sep-2024 11:51:01 Europe/Moscow] PHP Fatal error:  Uncaught Phalcon\Mvc\Model\Exception: Failed to store metaData to the cache adapter in /offload/rootfs/usr/www/src/Modules/PbxExtensionUtils.php:227
Stack trace:
#0 [internal function]: Phalcon\Mvc\Model\MetaData->throwWriteException(true)
#1 [internal function]: Phalcon\Mvc\Model\MetaData->write('map-mikopbx\\com...', Array)
#2 [internal function]: Phalcon\Mvc\Model\MetaData->initialize(Object(MikoPBX\Common\Models\PbxExtensionModules), NULL, NULL, NULL)
#3 [internal function]: Phalcon\Mvc\Model\MetaData->readColumnMapIndex(Object(MikoPBX\Common\Models\PbxExtensionModules), 1)
#4 [internal function]: Phalcon\Mvc\Model\MetaData->getReverseColumnMap(Object(MikoPBX\Common\Models\PbxExtensionModules))
#5 [internal function]: Phalcon\Mvc\Model\MetaData->hasAttribute(Object(MikoPBX\Common\Models\PbxExtensionModules), 'disabled')
#6 [internal function]: Phalcon\Mvc\Model\Query->_getQualified(Array)
#7 [internal function]: Phalcon\Mvc\Model\Query->_getExpression(Array, true)
#8 [internal function]: Phalcon\Mvc\Model in /offload/rootfs/usr/www/src/Modules/PbxExtensionUtils.php on line 227
[09-Sep-2024 12:15:31 Europe/Moscow] PHP Fatal error:  Uncaught RedisException: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error. in /offload/rootfs/usr/www/src/Common/Models/ModelsBase.php:261
Stack trace:
#0 [internal function]: Redis->del('PbxExtensionMod...')
#1 /offload/rootfs/usr/www/src/Common/Models/ModelsBase.php(261): Phalcon\Storage\Adapter\Redis->delete('PbxExtensionMod...')
#2 /offload/rootfs/usr/www/src/Common/Models/ModelsBase.php(124): MikoPBX\Common\Models\ModelsBase::clearCache('MikoPBX\\Common\\...')
#3 [internal function]: MikoPBX\Common\Models\ModelsBase->MikoPBX\Common\Models\{closure}(Object(Phalcon\Events\Event), Object(MikoPBX\Common\Models\PbxExtensionModules), NULL)
#4 [internal function]: Phalcon\Events\Manager->fireQueue(Object(SplPriorityQueue), in /offload/rootfs/usr/www/src/Common/Models/ModelsBase.php on line 261
`

![phalcon_1](https://github.com/user-attachments/assets/2ac8e9e7-ebba-49c9-abd4-5b78db7adb6b)

**Comment by jorikfon** [comment]
Добавил вышеописанную опцию в [MikoPBX 2024.2.28-dev](https://github.com/mikopbx/Core/releases/tag/2024.2.28-dev), посмотрим как это сработает. Хотя это не решение проблемы, а костыль вокруг нее. Не понятно как воспроизвести...

**Comment by boffart** [comment]
я такую проблему получил когда **tmpfs** был переполнен. 
```
~# df -h
Filesystem                Size      Used Available Use% Mounted on
devtmpfs                  1.4G    356.0K      1.4G   0% /dev
tmpfs                     2.5G     2.5G     0   2% /
/dev/vda2               301.1M    297.1M         0 100% /offload
/dev/vda3                12.8M    515.0K     11.3M   4% /cf
/dev/vdb1                19.5G     16.7G      1.8G  90% /storage/usbdisk1
cgroup                    1.4G         0      1.4G   0% /sys/fs/cgroup
```

**Comment by boffart** [comment]
При атаке на АТС fail2ban активно работает с таблицой sqlite3
`/var/lib/fail2ban/fail2ban.sqlite3` - этот файл ссылается на `/storage/usbdisk1/mikopbx/fail2ban/fail2ban.sqlite3`

Быстро растут временные файлы
`/var/lib/fail2ban/fail2ban.sqlite3-wal` - этот файл лежит в `/var` , в оперативной памяти. 
В итоге получаем переполнение RAM и падение АТС.

**Comment by ivstep** [comment]
MikoPBX 2024.1.114
Модуль резервного копирования 1.90

@boffart похожая проблема с tmpfs
Модуль резервного копирования забил раздел tmpfs. Модуль настроен на выгрузку по webDav.

<img width="642" alt="Image" src="https://github.com/user-attachments/assets/da5d9062-a67f-4e33-9b51-866cdaf14300" />
